from typing import List

# code in python for others benefit
class Question:
    def autocorrect(self, wordBank: List[str], word: str) -> str:
        if word in wordBank:
            return word

        list = []

        for str in wordBank:
            if len(str) != len(word):
                continue
            
            count = 0
            for i in range(len(word)):
                if word[i] != str[i]:
                    count += 1

            # if use zip we can code: count = sum(1 for a, b in zip(w, word) if a != b)

            if count == 1:
                list.append(str)

        list.sort()

        return list[0] if list else word


# Test cases generated by chatgpt
if __name__ == "__main__":
    wordBank = ["hello", "hallo", "hullo", "world", "wordl", "coder", "could"]
    q = Question()

    print(q.autocorrect(wordBank, "hella"))   # hello
    print(q.autocorrect(wordBank, "hello"))   # hello
    print(q.autocorrect(wordBank, "hillo"))   # hallo
    print(q.autocorrect(wordBank, "apple"))   # apple
    print(q.autocorrect(wordBank, "helloo"))  # helloo
